from __future__ import annotations

from pathlib import Path


LAKE_DIR = Path("LAKE")
OUTPUT_DIR = Path("saida")
CACHE_DIR = Path(".cache/diarios")
USER_AGENT = "exoneracoes-nomeacoes-dou/0.1 (+pesquisa civica)"

HTTP_DELAY_SECONDS = 1.0
HTTP_MAX_ATTEMPTS = 5
HTTP_TIMEOUT_SECONDS = 60

ENABLE_OCR = False
USE_DOCLING = True
DOCLING_DEVICE = "cuda"
DOCLING_NUM_THREADS = 2
DOCLING_FORCE_BACKEND_TEXT = True
DOCLING_DO_TABLE_STRUCTURE = False
DOCLING_DO_CODE_ENRICHMENT = False
DOCLING_DO_FORMULA_ENRICHMENT = False
DOCLING_DO_PICTURE_CLASSIFICATION = False
DOCLING_DO_PICTURE_DESCRIPTION = False
DOCLING_GENERATE_PAGE_IMAGES = False
DOCLING_GENERATE_PICTURE_IMAGES = False
DOCLING_GENERATE_TABLE_IMAGES = False
DOCLING_GENERATE_PARSED_PAGES = False
DOCLING_LAYOUT_BATCH_SIZE = 1
DOCLING_OCR_BATCH_SIZE = 1
DOCLING_TABLE_BATCH_SIZE = 1
TORCH_CUDA_RUNTIME = "11.8"

MARKDOWN_PARSE_BLOCK_SIZE = 1_000_000
MARKDOWN_PARSE_OVERLAP_SIZE = 2_000
