from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LAKE_DIR = PROJECT_ROOT / "LAKE"
OUTPUT_DIR = PROJECT_ROOT / "saida"
CACHE_DIR = PROJECT_ROOT / ".cache" / "diarios"
USER_AGENT = "exoneracoes-nomeacoes-dou/0.1 (+pesquisa civica)"

HTTP_DELAY_SECONDS = 1.0
HTTP_MAX_ATTEMPTS = 5
HTTP_TIMEOUT_SECONDS = 60

ENABLE_OCR = True
PRELOAD_OCR_MODELS = True
OCR_FALLBACK_MIN_CHARS = 500
OCR_FALLBACK_MIN_CHARS_PER_PAGE = 80
USE_DOCLING = True
DOCLING_DEVICE = "cuda"
DOCLING_NUM_THREADS = 8
DOCLING_FORCE_BACKEND_TEXT = True
DOCLING_DO_TABLE_STRUCTURE = True
DOCLING_DO_CODE_ENRICHMENT = False
DOCLING_DO_FORMULA_ENRICHMENT = False
DOCLING_DO_PICTURE_CLASSIFICATION = False
DOCLING_DO_PICTURE_DESCRIPTION = False
DOCLING_GENERATE_PAGE_IMAGES = False
DOCLING_GENERATE_PICTURE_IMAGES = False
DOCLING_GENERATE_TABLE_IMAGES = False
DOCLING_GENERATE_PARSED_PAGES = False
DOCLING_LAYOUT_BATCH_SIZE = 1
DOCLING_OCR_BATCH_SIZE = 1
DOCLING_TABLE_BATCH_SIZE = 1
DOCLING_PAGE_CHUNK_SIZE = 10
TORCH_CUDA_RUNTIME = "11.8"

MARKDOWN_PARSE_BLOCK_SIZE = 1_000_000
MARKDOWN_PARSE_OVERLAP_SIZE = 2_000

ENABLE_SPACY_VALIDATION = True
SPACY_MODEL = "pt_core_news_sm"
SPACY_MODE = "annotate"

SP_START_DATE = "2023-05-01"
SP_JOURNAL_NAME = "Executivo"
SP_SECTION_NAME = "Atos de Pessoal"
